"""
vt_markets/trading/order_manager.py
======================================
Order manager — orchestrates signal → risk calculation → execution.

Flow:
    Signal received
        ↓
    RiskManager.compute_order_specs()   (3 tiers)
        ↓
    For each spec: VTMarketsExecutor.buy() or .sell()
        ↓
    Store VTPosition
        ↓
    Notify PositionManager

Rules:
  - NO restriction on number of simultaneous positions
  - Opposite-direction signals are allowed
  - Multiple same-direction signals are allowed
  - Lots are validated before any order is placed
"""

from __future__ import annotations

import logging
from datetime import datetime

from vt_markets.models.position import VTPosition
from vt_markets.models.signal import Signal
from vt_markets.mt5.execution import VTMarketsExecutor
from vt_markets.trading.risk_manager import RiskManager, OrderSpec

logger = logging.getLogger(__name__)


class OrderManager:
    """
    Converts a Signal into three MT5 orders.

    Parameters
    ----------
    executor : VTMarketsExecutor
        The execution layer (abstraction over mt5.order_send).
    risk_manager : RiskManager
        Computes SL/TP tiers.
    on_position_opened : callable
        Called with each successfully opened VTPosition.
    on_position_failed : callable
        Called with each failed VTPosition (for logging).
    """

    def __init__(
        self,
        executor: VTMarketsExecutor,
        risk_manager: RiskManager,
        on_position_opened=None,
        on_position_failed=None,
    ) -> None:
        self._executor = executor
        self._risk_manager = risk_manager
        self._on_opened = on_position_opened or (lambda p: None)
        self._on_failed = on_position_failed or (lambda p: None)

    def handle_signal(self, signal: Signal) -> list[VTPosition]:
        """
        Process a signal: compute tiers, validate lots, send orders.

        Returns
        -------
        list[VTPosition]
            All positions (OPEN or FAILED) generated by this signal.
        """
        logger.info("Handling signal: %s", signal)

        specs = self._risk_manager.compute_order_specs(signal)
        if not specs:
            logger.warning("No valid order specs for signal %s — skipped.", signal)
            return []

        # Validate all lots against broker constraints BEFORE sending any order
        try:
            lots = [s.lot for s in specs]
            self._executor.validate_lots(lots)
        except ValueError as exc:
            logger.error(
                "Lot validation failed for %s signal: %s — no orders placed.",
                signal.strategy,
                exc,
            )
            return []

        positions: list[VTPosition] = []
        comment = f"{signal.strategy} {signal.direction}"

        for spec in specs:
            pos = self._send_order_for_spec(spec, signal, comment)
            pos.strategy = spec.strategy
            pos.risk_reward = spec.risk_reward
            pos.setup_time = signal.setup_time

            positions.append(pos)

            if pos.status == "OPEN":
                self._on_opened(pos)
            else:
                self._on_failed(pos)

        return positions

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _send_order_for_spec(
        self, spec: OrderSpec, signal: Signal, comment: str
    ) -> VTPosition:
        if spec.direction == "BUY":
            return self._executor.buy(
                lot=spec.lot,
                stop_loss=spec.stop_loss,
                take_profit=spec.take_profit,
                magic=spec.magic,
                comment=comment,
                setup_time=signal.setup_time,
            )
        else:
            return self._executor.sell(
                lot=spec.lot,
                stop_loss=spec.stop_loss,
                take_profit=spec.take_profit,
                magic=spec.magic,
                comment=comment,
                setup_time=signal.setup_time,
            )
